# Generated by Django 2.1.2 on 2019-01-01 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('profile', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('info_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'expert_intro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hometown',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('p2id', models.CharField(blank=True, max_length=255, null=True)),
                ('p1id', models.CharField(blank=True, max_length=255, null=True)),
                ('list', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hometown',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HometownRelation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hometown_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'hometown_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfluenceInfo',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('field', models.CharField(blank=True, max_length=255, null=True)),
                ('influ', models.FloatField(blank=True, null=True)),
                ('influ_19', models.FloatField(blank=True, null=True)),
                ('influ_1990', models.FloatField(blank=True, null=True)),
                ('influ_1995', models.FloatField(blank=True, null=True)),
                ('influ_2000', models.FloatField(blank=True, null=True)),
                ('influ_2005', models.FloatField(blank=True, null=True)),
                ('influ_2010', models.FloatField(blank=True, null=True)),
                ('influ_2015', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'influence_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfluenceTime',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('influ_1989', models.FloatField(blank=True, null=True)),
                ('influ_1990', models.FloatField(blank=True, null=True)),
                ('influ_1991', models.FloatField(blank=True, null=True)),
                ('influ_1992', models.FloatField(blank=True, null=True)),
                ('influ_1993', models.FloatField(blank=True, null=True)),
                ('influ_1994', models.FloatField(blank=True, null=True)),
                ('influ_1995', models.FloatField(blank=True, null=True)),
                ('influ_1996', models.FloatField(blank=True, null=True)),
                ('influ_1997', models.FloatField(blank=True, null=True)),
                ('influ_1998', models.FloatField(blank=True, null=True)),
                ('influ_1999', models.FloatField(blank=True, null=True)),
                ('influ_2000', models.FloatField(blank=True, null=True)),
                ('influ_2001', models.FloatField(blank=True, null=True)),
                ('influ_2002', models.FloatField(blank=True, null=True)),
                ('influ_2003', models.FloatField(blank=True, null=True)),
                ('influ_2004', models.FloatField(blank=True, null=True)),
                ('influ_2005', models.FloatField(blank=True, null=True)),
                ('influ_2006', models.FloatField(blank=True, null=True)),
                ('influ_2007', models.FloatField(blank=True, null=True)),
                ('influ_2008', models.FloatField(blank=True, null=True)),
                ('influ_2009', models.FloatField(blank=True, null=True)),
                ('influ_2010', models.FloatField(blank=True, null=True)),
                ('influ_2011', models.FloatField(blank=True, null=True)),
                ('influ_2012', models.FloatField(blank=True, null=True)),
                ('influ_2013', models.FloatField(blank=True, null=True)),
                ('influ_2014', models.FloatField(blank=True, null=True)),
                ('influ_2015', models.FloatField(blank=True, null=True)),
                ('influ_2016', models.FloatField(blank=True, null=True)),
                ('influ_2017', models.FloatField(blank=True, null=True)),
                ('influ_2018', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'influ_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpinionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'opinion_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpinionRaw',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('expert_id', models.CharField(db_index=True, max_length=255)),
                ('expert_name', models.CharField(blank=True, max_length=255, null=True)),
                ('expert_university', models.CharField(blank=True, max_length=255, null=True)),
                ('expert_college', models.CharField(blank=True, max_length=255, null=True)),
                ('expert_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.CharField(blank=True, max_length=255, null=True)),
                ('article_url', models.TextField(blank=True, null=True)),
                ('article_title', models.TextField(blank=True, null=True)),
                ('article_source', models.TextField(blank=True, null=True)),
                ('article_time', models.TextField(blank=True, null=True)),
                ('article_brief', models.TextField(blank=True, null=True)),
                ('snapshot_url', models.TextField(blank=True, null=True)),
                ('analysis_tag', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'opinion_raw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('col', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('attach', models.CharField(blank=True, max_length=255, null=True)),
                ('loc', models.CharField(blank=True, max_length=255, null=True)),
                ('teach', models.CharField(blank=True, max_length=255, null=True)),
                ('con', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('intro', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'organization_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaperRelation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('coid_list', models.CharField(blank=True, max_length=255, null=True)),
                ('year_list', models.CharField(blank=True, max_length=255, null=True)),
                ('score_list', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'paper_relation_score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PapersTime',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('paper_1989', models.FloatField(blank=True, null=True)),
                ('paper_1990', models.FloatField(blank=True, null=True)),
                ('paper_1991', models.FloatField(blank=True, null=True)),
                ('paper_1992', models.FloatField(blank=True, null=True)),
                ('paper_1993', models.FloatField(blank=True, null=True)),
                ('paper_1994', models.FloatField(blank=True, null=True)),
                ('paper_1995', models.FloatField(blank=True, null=True)),
                ('paper_1996', models.FloatField(blank=True, null=True)),
                ('paper_1997', models.FloatField(blank=True, null=True)),
                ('paper_1998', models.FloatField(blank=True, null=True)),
                ('paper_1999', models.FloatField(blank=True, null=True)),
                ('paper_2000', models.FloatField(blank=True, null=True)),
                ('paper_2001', models.FloatField(blank=True, null=True)),
                ('paper_2002', models.FloatField(blank=True, null=True)),
                ('paper_2003', models.FloatField(blank=True, null=True)),
                ('paper_2004', models.FloatField(blank=True, null=True)),
                ('paper_2005', models.FloatField(blank=True, null=True)),
                ('paper_2006', models.FloatField(blank=True, null=True)),
                ('paper_2007', models.FloatField(blank=True, null=True)),
                ('paper_2008', models.FloatField(blank=True, null=True)),
                ('paper_2009', models.FloatField(blank=True, null=True)),
                ('paper_2010', models.FloatField(blank=True, null=True)),
                ('paper_2011', models.FloatField(blank=True, null=True)),
                ('paper_2012', models.FloatField(blank=True, null=True)),
                ('paper_2013', models.FloatField(blank=True, null=True)),
                ('paper_2014', models.FloatField(blank=True, null=True)),
                ('paper_2015', models.FloatField(blank=True, null=True)),
                ('paper_2016', models.FloatField(blank=True, null=True)),
                ('paper_2017', models.FloatField(blank=True, null=True)),
                ('paper_2018', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'papers_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThemeRelation',
            fields=[
                ('hash', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('expert_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'theme_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount1', models.IntegerField(blank=True, null=True)),
                ('amount2', models.IntegerField(blank=True, null=True)),
                ('h_index', models.IntegerField(blank=True, null=True)),
                ('core', models.CharField(blank=True, max_length=255, null=True)),
                ('cssci', models.CharField(blank=True, max_length=255, null=True)),
                ('rdfybkzl', models.CharField(blank=True, max_length=255, null=True)),
                ('co_expert', models.CharField(blank=True, max_length=255, null=True)),
                ('co_agency', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'academic_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
                ('theme_list', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_list', models.CharField(blank=True, max_length=255, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('url1', models.CharField(blank=True, max_length=255, null=True)),
                ('url2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '专家基本信息',
                'verbose_name_plural': '专家基本信息',
                'db_table': 'basic_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExpertGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='专家分组名')),
                ('expert_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '专家分组信息',
                'verbose_name_plural': '专家分组信息',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(db_index=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '自定义用户',
                'verbose_name_plural': '自定义用户',
            },
        ),
        migrations.CreateModel(
            name='PaperInfo',
            fields=[
                ('paper_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('authors', models.CharField(blank=True, max_length=255, null=True)),
                ('author1', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('author2', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('author3', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('author4', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('author5', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'paper_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
    ]
