# Generated by Django 2.1.5 on 2019-03-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDMS_backend', '0002_auto_20190304_1026'),
    ]

    operations = [

        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
