# Generated by Django 2.1.5 on 2019-03-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EDMS_backend', '0003_auto_20190304_1538'),
    ]

    operations = [

        migrations.AlterModelOptions(
            name='basicinfo',
            options={'managed': True, 'verbose_name': '专家信息', 'verbose_name_plural': '专家信息'},
        ),
        migrations.AddField(
            model_name='myuser',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
